services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "8080:80"
    volumes:
    - ./html:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -php
    networks:
      - dc_app-net

  php:
    build:
      context: ./docker/php
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - dc_app-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

networks:
  - dc_app-net
volumes:
  mysql_data:
